spring.application.name=backend
spring.mongodb.uri=mongodb://localhost:27017/studoc-share

server.servlet.context-path=/api/v1.0

spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://infinite-lark-50.clerk.accounts.dev
clerk.jwks-url=https://infinite-lark-50.clerk.accounts.dev/.well-known/jwks.json