spring.application.name=backend
spring.mongodb.uri=mongodb://localhost:27017/studoc-share

server.servlet.context-path=/api/v1.0

spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Clerk Configuration
clerk.issuer=https://infinite-lark-50.clerk.accounts.dev
clerk.jwks-url=https://infinite-lark-50.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}
clerk.secret.key=${CLERK_SECRET_KEY}

# File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

# Cloudinary Configuration
cloudinary.cloud-name=dz32nqnp3
cloudinary.api-key=535356454445185
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Gemini API Configuration
gemini.api.key=${GEMINI_API_KEY}
gemini.api.base-url=https://generativelanguage.googleapis.com/v1beta
gemini.model=gemini-2.5-flash
